# Form implementation generated from reading ui file 'knowledge_base_view.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_kb_window(object):
    def setupUi(self, kb_window):
        kb_window.setObjectName("kb_window")
        kb_window.resize(800, 600)
        self.kb_central_widget = QtWidgets.QWidget(parent=kb_window)
        self.kb_central_widget.setObjectName("kb_central_widget")
        self.kb_central_frame = QtWidgets.QFrame(parent=self.kb_central_widget)
        self.kb_central_frame.setGeometry(QtCore.QRect(0, 0, 800, 558))
        self.kb_central_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.kb_central_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.kb_central_frame.setObjectName("kb_central_frame")
        self.kb_tree_list = QtWidgets.QTreeWidget(parent=self.kb_central_frame)
        self.kb_tree_list.setGeometry(QtCore.QRect(0, 0, 250, 558))
        self.kb_tree_list.setObjectName("kb_tree_list")
        item_0 = QtWidgets.QTreeWidgetItem(self.kb_tree_list)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.kb_tree_list)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.kb_tree_list)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.kb_tree_list)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.kb_tree_list)
        self.kb_browser = QtWidgets.QTextBrowser(parent=self.kb_central_frame)
        self.kb_browser.setGeometry(QtCore.QRect(255, 5, 540, 548))
        self.kb_browser.setObjectName("kb_browser")
        kb_window.setCentralWidget(self.kb_central_widget)
        self.menubar = QtWidgets.QMenuBar(parent=kb_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        kb_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=kb_window)
        self.statusbar.setObjectName("statusbar")
        kb_window.setStatusBar(self.statusbar)

        self.retranslateUi(kb_window)
        QtCore.QMetaObject.connectSlotsByName(kb_window)

    def retranslateUi(self, kb_window):
        _translate = QtCore.QCoreApplication.translate
        kb_window.setWindowTitle(_translate("kb_window", "MainWindow"))
        self.kb_tree_list.headerItem().setText(0, _translate("kb_window", "Knowledge Base"))
        __sortingEnabled = self.kb_tree_list.isSortingEnabled()
        self.kb_tree_list.setSortingEnabled(False)
        self.kb_tree_list.topLevelItem(0).setText(0, _translate("kb_window", "Linear Regression"))
        self.kb_tree_list.topLevelItem(0).child(0).setText(0, _translate("kb_window", "Formula"))
        self.kb_tree_list.topLevelItem(0).child(1).setText(0, _translate("kb_window", "Description"))
        self.kb_tree_list.topLevelItem(1).setText(0, _translate("kb_window", "Ridge Regression"))
        self.kb_tree_list.topLevelItem(1).child(0).setText(0, _translate("kb_window", "Formula"))
        self.kb_tree_list.topLevelItem(1).child(1).setText(0, _translate("kb_window", "Description"))
        self.kb_tree_list.topLevelItem(2).setText(0, _translate("kb_window", "Preprocessing"))
        self.kb_tree_list.topLevelItem(2).child(0).setText(0, _translate("kb_window", "Standardisation"))
        self.kb_tree_list.topLevelItem(3).setText(0, _translate("kb_window", "Evaluation"))
        self.kb_tree_list.topLevelItem(3).child(0).setText(0, _translate("kb_window", "Mean Absolute Error (MAE)"))
        self.kb_tree_list.topLevelItem(3).child(1).setText(0, _translate("kb_window", "Mean Squared Error (MSE)"))
        self.kb_tree_list.topLevelItem(3).child(2).setText(0, _translate("kb_window", "R-Squared (R2)"))
        self.kb_tree_list.topLevelItem(4).setText(0, _translate("kb_window", "F.A.Q"))
        self.kb_tree_list.setSortingEnabled(__sortingEnabled)
